server:
  port: 8070

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      routes:
        - id: notification-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/notifications/**

        - id: customer-service
          uri: http://localhost:8081
          predicates:
            - Path=/customers/**

        - id: flight-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/flights/**

        - id: luggage-service
          uri: http://localhost:7074
          predicates:
            - Path=/api/v1/luggage/**

        - id: backoffice-service
          uri: http://localhost:8089
          predicates:
            - Path=/backoffice/**

        - id: auth-service
          uri: http://localhost:7078
          predicates:
            - Path=/api/auth/**
      default-filters:
        - name : AuthenticationFilter



eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8671/eureka/
